name: 'Deploy ETL to Google Cloud Functions'

on:
  push:
    branches:
    - "stg"
    - "dev"

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_PROJECT_NUMBER: ${{ vars.GCP_PROJECT_NUMBER }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GCS_BUCKET_NAME: ${{ vars.GCS_BUCKET_NAME }}
  DATASET: ${{ vars.DATASET }}
  API_URL: ${{ vars.API_URL }}
  SERVICE_ACCOUNT_RUNTIME: ${{ vars.SERVICE_ACCOUNT_RUNTIME }}
  SERVICE_ACCOUNT_GH: ${{ vars.SERVICE_ACCOUNT_GH }}
  WIF_POOL_ID: ${{ vars.WIF_POOL_ID }} # Workload Identity Federation Pool
  WIF_POOL_PROVIDER: ${{ vars.WIF_POOL_PROVIDER }} # Workload Identity Federation Provider
  PROJECT: ${{ vars.PROJECT }}
  STREAM: ${{ vars.STREAM }}
  PUBSUB_TOPIC_INGEST: ${{ vars.PUBSUB_TOPIC_INGEST }}
  PUBSUB_TOPIC_TRANSFORM: ${{ vars.PUBSUB_TOPIC_TRANSFORM }}
  UV_VERSION: 0.7.8 # Version of uv to install

jobs:

  pre-commit:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Install a specific version of uv.
        version: ${{ env.UV_VERSION }}

    - name: Install dependencies
      run:  make install

    - name: pre-commit run
      run: make pre-commit

  tests:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    needs: pre-commit

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Install a specific version of uv.
        version: ${{ env.UV_VERSION }}

    - name: tests
      run: make tests

  etl:
    strategy:
      matrix:
        cloud_function: [extract, transform, load]
        include:
        - cloud_function: extract
          trigger: http
        - cloud_function: transform
          trigger: topic transformation
        - cloud_function: load
          trigger: topic ingestion
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    needs: [pre-commit, tests]

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v4

    - name: Authentication to Google Cloud Platform
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: 'projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL_ID }}/providers/${{ env.WIF_POOL_PROVIDER }}'
        service_account: ${{ env.SERVICE_ACCOUNT_GH }}
        access_token_lifetime: 300s

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Install a specific version of uv.
        version: ${{ env.UV_VERSION }}

    - name: Copy source code to Cloud Function directory
      run: |
        mkdir -p cloud_function_${{ matrix.cloud_function }}
        cp -r src/ cloud_function_${{ matrix.cloud_function }}/src
        mv main_${{ matrix.cloud_function }}.py cloud_function_${{ matrix.cloud_function }}/main.py
        uv export --no-hashes --no-header --no-annotate --format requirements.txt > cloud_function_${{ matrix.cloud_function }}/requirements.txt

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy ${{ env.PROJECT }}-${{ env.STREAM }}-${{ matrix.cloud_function }} \
        --gen2 \
        --region=${{ env.GCP_REGION }} \
        --runtime=python313 \
        --memory=1G \
        --source=cloud_function_${{ matrix.cloud_function }} \
        --trigger-${{ matrix.trigger }} \
        --entry-point=${{ matrix.cloud_function }} \
        --no-allow-unauthenticated \
        --ingress-settings=internal-only \
        --run-service-account=${{ env.SERVICE_ACCOUNT_RUNTIME }} \
        --build-service-account=projects/${{ env.GCP_PROJECT_ID }}/serviceAccounts/${{ env.SERVICE_ACCOUNT_GH }} \
        --set-env-vars GCS_BUCKET_NAME=${{ env.GCS_BUCKET_NAME }} \
        --set-env-vars GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }} \
        --set-env-vars DATASET=${{ env.DATASET }} \
        --set-env-vars API_URL=${{ env.API_URL }} \
        --set-env-vars PUBSUB_TOPIC_INGEST=${{ env.PUBSUB_TOPIC_INGEST }} \
        --set-env-vars PUBSUB_TOPIC_TRANSFORM=${{ env.PUBSUB_TOPIC_TRANSFORM }}
